language: swift
osx_image: xcode7.3
xcode_project: Example/PieOverlayMenu.xcodeproj
xcode_scheme: PieOverlayMenu
xcode_sdk: iphonesimulator9.3
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'PieOverlayMenu'